### ISSUE TITLE
ECHOS is not a common word

### ISSUE THREAD

**Issue by jorendorff** [skedwards88/word_lists#5]
Dictionaries seem to agree that the plural of "echo" is always spelled "echoes".

There is a Wikipedia article for [something named Echos](https://en.wikipedia.org/wiki/Echos) in Byzantine music.

**Comment by skedwards88** [comment]
Thank you! Fixed in https://github.com/skedwards88/word_lists/commit/dd554866d8d6bc09ab8dc727aded9fe89800732e.
